-
  name: 'WebExcess.Notifications script'
  uriPattern:    'neos/webexcess/notifications/get'
  defaults:
    '@package':    'WebExcess.Notifications'
    '@controller': 'Notification'
    '@action': 'get'
  httpMethods: ['GET']
  appendExceedingArguments: TRUE